[package]
name = "otbr-client"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
twine-codec.workspace = true
zbus.workspace = true
