[package]
name = "otbr-client"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
thiserror.workspace = true
twine-codec = { path = "../twine-codec", features = ["alloc"] }
zbus.workspace = true
