[package]
name = "twine-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4.20"
nix = { version = "0.27.1", features = ["net"] }
socket2 = "0.5.4"
